## Hydrogen TorchでPredictionで取得できる結果ファイルに関して

Hydrogen Torchで学習済みモデルを利用してPredictionを実施すると、以下のcsvとpklファイルがダウンロードできる

In [5]:
!ls preds_ml-market_round5_augmentations_strategy_Medium_pool_Average.fold0.predict_fold0

test_predictions.csv     test_raw_predictions.pkl


In [41]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('preds_ml-market_round5_augmentations_strategy_Medium_pool_Average.fold0.predict_fold0/test_predictions.csv')
df

image_id  label      top_1_similar_image  \
0    0806_c6s2_088893_10.jpg    806  0806_c3s2_094853_01.jpg   
1    1106_c2s2_147252_01.jpg   1106  1106_c2s2_147302_06.jpg   
2    1422_c3s3_057028_06.jpg   1422  0839_c2s2_104182_01.jpg   
3    0662_c3s2_040037_03.jpg    662  1415_c3s3_074669_05.jpg   
4    1231_c1s6_044221_02.jpg   1231  1140_c3s3_070894_01.jpg   
..                       ...    ...                      ...   
716  0871_c3s2_108253_04.jpg    871  0871_c2s2_105582_07.jpg   
717  1099_c2s2_145927_04.jpg   1099  1099_c2s2_145802_01.jpg   
718  0402_c3s1_095517_02.jpg    402  0402_c3s1_095542_01.jpg   
719  1072_c2s3_097677_01.jpg   1072  1072_c2s3_097777_01.jpg   
720  1099_c1s5_013086_03.jpg   1099  1099_c1s5_013111_02.jpg   

     top_1_cosine_similarity      top_2_similar_image  \
0                   0.940281  0529_c2s1_148416_03.jpg   
1                   0.925393  1471_c1s6_011416_01.jpg   
2                   0.275027  0700_c6s2_048093_03.jpg   
3                   0.548925  0190_c2s3_072102_02.jpg   
4                   0.535775  0379_c2s1_089071_02.jpg   
..                       ...                      ...   
716                 0.586493  0871_c2s2_105607_04.jpg   
717                 0.604163  0528_c1s3_007046_04.jpg   
718                 0.924879  0402_c5s1_096223_06.jpg   
719                 0.609177  1072_c3s3_104094_06.jpg   
720                 0.686175  0528_c1s3_007046_04.jpg   

     top_2_cosine_similarity      top_3_similar_image  top_3_cosine_similarity  
0                   0.350552  0864_c3s2_107903_04.jpg                 0.312094  
1                   0.255338  1471_c1s6_011366_01.jpg                 0.236654  
2                   0.236710  0566_c3s2_004612_02.jpg                 0.236667  
3                   0.448412  0392_c4s2_018467_03.jpg                 0.289325  
4                   0.453505  0515_c3s1_141658_03.jpg                 0.449389  
..                       ...                      ...                      ...  
716                 0.560050  0871_c2s2_105582_04.jpg                 0.460217  
717                 0.530871  0549_c1s3_009921_05.jpg                 0.475304  
718                 0.837170  0402_c2s1_095371_01.jpg                 0.783164  
719                 0.508429  1072_c6s4_030577_09.jpg                 0.487599  
720                 0.543222  0588_c6s3_090992_01.jpg                 0.477783  

[721 rows x 8 columns]

In [14]:
pkl = pd.read_pickle('preds_ml-market_round5_augmentations_strategy_Medium_pool_Average.fold0.predict_fold0/test_raw_predictions.pkl')
type(pkl)

dict

In [16]:
pkl.keys()

dict_keys(['embeddings', 'cosine_similarities', 'similar_images', 'image_id'])

### embeddings
(画像枚数、検索ベクトル次元)  
検索ベクトルの次元数は、モデル作成時に指定した次元

In [19]:
pkl['embeddings'].shape

(721, 256)

In [26]:
pkl['embeddings'][:10, :5]

array([[ 1.6398124 ,  1.170287  ,  0.79744625,  2.998584  ,  1.1577348 ],
       [ 0.5453316 , -0.1095092 , -0.06442223,  1.4211079 , -0.6957893 ],
       [-1.1842227 ,  0.01390333, -0.64168704, -0.5241634 , -0.8966926 ],
       [ 3.0031054 , -1.8206494 , -0.85749793,  0.29363796, -0.08301008],
       [ 0.6488145 ,  0.2051069 , -0.6285773 ,  0.30053654, -1.520156  ],
       [ 0.87946635,  0.11738975, -0.4545608 , -0.37383714, -0.41292605],
       [-1.2107159 , -1.729303  , -2.3574762 ,  0.15786694, -0.18645708],
       [-0.71217906,  0.54496926,  1.434429  , -0.24268219, -0.8351129 ],
       [ 1.389871  ,  1.6104366 ,  0.6099144 , -2.0162287 ,  1.262106  ],
       [ 1.2063247 ,  0.65634423, -0.17763661,  0.9300512 , -1.0998803 ]],
      dtype=float32)

### cosine_similarities
(画像枚数、類似上位50画像のコサイン類似度)  

In [21]:
pkl['cosine_similarities'].shape

(721, 50)

In [73]:
print('{} と類似した上位50画像とのコサイン類似度'.format(df.loc[0, 'image_id']))
pkl['cosine_similarities'][0,:]

0806_c6s2_088893_10.jpg と類似した上位50画像とのコサイン類似度


array([1.        , 0.94028056, 0.35055184, 0.3120944 , 0.27041876,
       0.2655021 , 0.23886728, 0.22951023, 0.22620165, 0.20627016,
       0.20406446, 0.1992691 , 0.19908944, 0.19853538, 0.19126937,
       0.19023725, 0.18864374, 0.18836144, 0.18811636, 0.18587422,
       0.18198632, 0.17720407, 0.17444804, 0.17269425, 0.17234688,
       0.16216266, 0.1605659 , 0.16000679, 0.15689033, 0.15656313,
       0.1546832 , 0.15227385, 0.15149283, 0.15092051, 0.1500732 ,
       0.14847201, 0.14669168, 0.14633855, 0.14561892, 0.14546742,
       0.14458139, 0.14281389, 0.1407694 , 0.14021844, 0.13890241,
       0.1377278 , 0.13457842, 0.13395295, 0.13297963, 0.13282338],
      dtype=float32)

In [30]:
def cos_sim(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [74]:
df[df['image_id']=='0806_c3s2_094853_01.jpg']   # 1番類似している画像

image_id  label      top_1_similar_image  \
312  0806_c3s2_094853_01.jpg    806  0806_c6s2_088893_10.jpg   

     top_1_cosine_similarity      top_2_similar_image  \
312                 0.940281  0529_c2s1_148416_03.jpg   

     top_2_cosine_similarity      top_3_similar_image  top_3_cosine_similarity  
312                 0.392337  0864_c3s2_107903_04.jpg                 0.354492

In [75]:
idx = df[df['image_id']=='0806_c3s2_094853_01.jpg'].index[0]
print(idx)
pkl['cosine_similarities'][idx,:]

312


array([1.        , 0.94028056, 0.3923371 , 0.35449207, 0.31615618,
       0.27990934, 0.24694756, 0.22971949, 0.21657586, 0.20553778,
       0.20251378, 0.188428  , 0.18755712, 0.18750112, 0.18710615,
       0.18382469, 0.18038675, 0.18022421, 0.17522779, 0.17436096,
       0.17284915, 0.17275351, 0.17200261, 0.17104515, 0.16906054,
       0.16747378, 0.16647834, 0.16558881, 0.16522035, 0.1636498 ,
       0.16336213, 0.15889491, 0.15783687, 0.1570262 , 0.15626314,
       0.15264973, 0.14894149, 0.14770815, 0.14652765, 0.14524058,
       0.14481041, 0.14373538, 0.14320585, 0.14292237, 0.1406737 ,
       0.13792059, 0.13691899, 0.13691899, 0.13557279, 0.13555592],
      dtype=float32)

In [76]:
cos_sim(pkl['embeddings'][0,:], pkl['embeddings'][idx,:])

0.94028056

In [77]:
pkl['cosine_similarities'][0,1]

0.94028056

In [78]:
# 一致

### similar_images
(画像枚数、類似上位50画像のindex)  

In [81]:
pkl['similar_images'].shape

(721, 50)

In [82]:
pkl['similar_images']

array([[  0, 312,  86, ..., 561, 619, 621],
       [  1, 450, 206, ..., 452,  82, 226],
       [  2, 456, 212, ..., 190,  42,  81],
       ...,
       [718, 643, 639, ..., 695, 658, 510],
       [719, 679, 701, ..., 421, 420, 224],
       [720, 651,  53, ..., 247, 445, 426]])

In [83]:
pkl['similar_images'].min(), pkl['similar_images'].max()

(0, 720)

### image_id
画像ファイル名

In [85]:
pkl['image_id'].shape

(721,)

In [87]:
pkl['image_id'][:10]

array(['0806_c6s2_088893_10.jpg', '1106_c2s2_147252_01.jpg',
       '1422_c3s3_057028_06.jpg', '0662_c3s2_040037_03.jpg',
       '1231_c1s6_044221_02.jpg', '0901_c6s2_105193_02.jpg',
       '1453_c3s3_057728_02.jpg', '1313_c6s3_078267_01.jpg',
       '0970_c4s4_062716_02.jpg', '0546_c2s1_157341_03.jpg'], dtype=object)