## Hydrogen Torch - Metric Learning Prediction Download File
Hydrogen Torchで距離学習モデルを作成。任意のデータに対して予測（Predict）を実施し、結果ファイルをダウンロード

In [44]:
import pandas as pd
import numpy as np

In [4]:
!ls prediction/preds_ml-baseline.fold0.predict.1_fold0

test_predictions.csv     test_raw_predictions.pkl


### csvファイル

In [13]:
df = pd.read_csv('prediction/preds_ml-baseline.fold0.predict.1_fold0/test_predictions.csv')
df.shape

(1663, 9)

In [14]:
df.head()

image         label  fold top_1_similar_image  \
0  151414046745_8.JPG  151414046745     4  151414046745_0.JPG   
1  251747828037_1.JPG  251747828037     4  251747828037_0.JPG   
2  400957457012_3.JPG  400957457012     4  400957457012_2.JPG   
3  111733215174_2.JPG  111733215174     4  111733215174_3.JPG   
4  131567176523_4.JPG  131567176523     4  131567176523_3.JPG   

   top_1_cosine_similarity  top_2_similar_image  top_2_cosine_similarity  \
0                 0.788647   151414046745_2.JPG                 0.725330   
1                 0.998313   111733238663_1.JPG                 0.610985   
2                 0.842128  400957457012_11.JPG                 0.812825   
3                 0.882937   111733215174_4.JPG                 0.877927   
4                 0.779511   131567176523_2.JPG                 0.678530   

  top_3_similar_image  top_3_cosine_similarity  
0  151414046745_4.JPG                 0.689846  
1  111733238663_0.JPG                 0.610985  
2  400957457012_9.JPG                 0.772822  
3  111733215174_8.JPG                 0.744403  
4  400965651388_1.JPG                 0.668002

各画像（1663枚）と類似上位3位画像の画像ファイル名と類似度（コサイン類似度）

### pklファイル

In [8]:
pk = pd.read_pickle('prediction/preds_ml-baseline.fold0.predict.1_fold0/test_raw_predictions.pkl')
type(pk)

dict

In [9]:
pk

{'embeddings': array([[ 1.07497168e+00, -1.21398404e-01, -5.81534863e-01, ...,
         -2.33517125e-01, -2.40838990e-01,  3.78616512e-01],
        [ 2.27141142e-01,  1.77186489e+00,  8.70964348e-01, ...,
         -4.30517375e-01, -7.96101809e-01,  5.22936583e-01],
        [-6.00740016e-01,  1.05046737e+00,  1.08377767e+00, ...,
         -1.01552240e-03,  3.60473394e-02, -1.11484683e+00],
        ...,
        [-2.72388667e-01,  3.10453385e-01,  1.24150634e+00, ...,
          1.23785269e+00,  9.01244104e-01, -7.89174020e-01],
        [ 1.45416343e+00, -1.59152299e-02,  1.25278875e-01, ...,
         -4.17469770e-01, -6.05662644e-01,  4.07367289e-01],
        [ 2.33735129e-01,  8.54482472e-01,  1.24066162e+00, ...,
          1.37019730e+00, -2.31863737e-01,  3.44229788e-02]], dtype=float32),
 'cosine_similarities': array([[1.0000001 , 0.7886466 , 0.72532964, ..., 0.38408548, 0.3743736 ,
         0.37117776],
        [1.        , 0.998313  , 0.61098546, ..., 0.36415392, 0.35697114,
       

In [10]:
pk.keys()

dict_keys(['embeddings', 'cosine_similarities', 'similar_images', 'image'])

画像ファイル名

In [20]:
pk['image'].shape

(1663,)

In [21]:
pk['image'][:10]

array(['151414046745_8.JPG', '251747828037_1.JPG', '400957457012_3.JPG',
       '111733215174_2.JPG', '131567176523_4.JPG', '141728384307_1.JPG',
       '270985868152_3.JPG', '391215659246_8.JPG', '221604069261_0.JPG',
       '381346919985_2.JPG'], dtype=object)

各画像の512次元のEmbedding（モデル作成時に512次元を指定）

In [12]:
pk['embeddings'].shape

(1663, 512)

In [23]:
pk['embeddings'][:10, :]

array([[ 1.07497168e+00, -1.21398404e-01, -5.81534863e-01, ...,
        -2.33517125e-01, -2.40838990e-01,  3.78616512e-01],
       [ 2.27141142e-01,  1.77186489e+00,  8.70964348e-01, ...,
        -4.30517375e-01, -7.96101809e-01,  5.22936583e-01],
       [-6.00740016e-01,  1.05046737e+00,  1.08377767e+00, ...,
        -1.01552240e-03,  3.60473394e-02, -1.11484683e+00],
       ...,
       [ 3.71872842e-01,  6.65462196e-01, -6.79864347e-01, ...,
         4.51503873e-01,  1.52752805e+00, -3.21243972e-01],
       [ 3.33166659e-01,  1.92360088e-01, -9.72405970e-01, ...,
        -6.13723338e-01,  9.40580010e-01, -4.59785789e-01],
       [-2.38814205e-01,  1.38348818e+00, -1.66326389e-01, ...,
         7.76580095e-01,  2.09778810e+00, -1.96519479e-01]], dtype=float32)

**データフレームで、画像ファイル名に対応するEmbeddingを表示してみる**

In [27]:
pd.DataFrame({'image':pk['image']}).join(pd.DataFrame(pk['embeddings']))

image         0         1         2         3         4  \
0     151414046745_8.JPG  1.074972 -0.121398 -0.581535 -0.082283 -0.030870   
1     251747828037_1.JPG  0.227141  1.771865  0.870964 -0.429514 -0.139533   
2     400957457012_3.JPG -0.600740  1.050467  1.083778  0.781974 -0.630697   
3     111733215174_2.JPG -0.074577  2.241524 -0.397442 -0.711581  1.338481   
4     131567176523_4.JPG -0.721359  0.900395 -0.968041  1.250843  0.085651   
...                  ...       ...       ...       ...       ...       ...   
1658  231634042205_1.JPG -0.779147  1.303374  1.779549  0.061459  0.875013   
1659  261617986263_1.JPG -0.149124 -0.301009  0.618842 -0.457302 -0.117831   
1660  121715580427_3.JPG -0.272389  0.310453  1.241506  1.372070 -0.027258   
1661  331602923356_7.JPG  1.454163 -0.015915  0.125279 -1.960235  1.101515   
1662  301702155234_8.JPG  0.233735  0.854482  1.240662  0.240128  0.252319   

             5         6         7         8  ...       502       503  \
0    -0.725494  1.652115  0.024447  1.342337  ... -0.503952  1.132980   
1     0.466942 -0.167227 -0.305729 -0.365382  ... -0.066853  0.435738   
2    -0.578733 -0.280022  2.251088 -0.397303  ... -0.418795 -0.414978   
3     1.501900 -0.554181 -0.121256 -1.152586  ...  0.378851  0.481882   
4     0.149362  0.432996 -0.271541  0.266092  ... -0.340295 -0.037362   
...        ...       ...       ...       ...  ...       ...       ...   
1658  0.862360 -0.503638 -0.012851 -0.586948  ...  1.129666 -0.333828   
1659 -0.090237 -0.541397 -0.444439 -0.340010  ...  0.243571  0.121702   
1660  1.711316 -0.037880  0.722389  1.280954  ... -0.006283  0.149002   
1661 -0.103076 -0.136933 -0.240850  0.821685  ...  1.209847  0.093527   
1662 -0.508262 -0.622278  0.287419 -0.200333  ... -0.081030  0.080638   

           504       505       506       507       508       509       510  \
0    -0.004669  0.391195 -0.038441  0.483147 -0.190056 -0.233517 -0.240839   
1     0.250023  1.152870 -0.051964  0.084344  0.519142 -0.430517 -0.796102   
2    -0.725062  1.214044 -0.243604  0.329307 -0.765241 -0.001016  0.036047   
3     0.690869  0.248687  0.779890  1.877414 -0.097610 -1.207974  0.574088   
4     0.293109  0.147440  0.219687 -0.362342 -0.102005 -0.447061  1.690927   
...        ...       ...       ...       ...       ...       ...       ...   
1658  0.485395  0.139858  1.460458  0.851156 -0.239571  0.384492 -0.574597   
1659 -0.432326  1.018678 -0.555260 -0.703385 -0.745569 -0.049803 -0.827218   
1660 -0.659014 -1.413185 -0.124710  1.361771 -0.008666  1.237853  0.901244   
1661  1.370615  1.822390 -0.001915  2.007416  0.913311 -0.417470 -0.605663   
1662 -0.585312  0.921660  0.371529 -0.013860 -0.006327  1.370197 -0.231864   

           511  
0     0.378617  
1     0.522937  
2    -1.114847  
3     1.241420  
4     0.086309  
...        ...  
1658  1.044144  
1659 -0.816545  
1660 -0.789174  
1661  0.407367  
1662  0.034423  

[1663 rows x 513 columns]

コサイン類似度
- 上位50位まで（予測実施時に設定可能）の画像（index）とコサイン類似度

In [15]:
pk['cosine_similarities'].shape

(1663, 50)

In [28]:
pk['cosine_similarities'][:, :10]

array([[1.0000001 , 0.7886466 , 0.72532964, ..., 0.5875672 , 0.5801832 ,
        0.5326115 ],
       [1.        , 0.998313  , 0.61098546, ..., 0.59150964, 0.59150964,
        0.59150964],
       [1.0000001 , 0.84212756, 0.81282496, ..., 0.64939153, 0.64452255,
        0.59284896],
       ...,
       [1.        , 0.79817027, 0.727471  , ..., 0.65001094, 0.6473901 ,
        0.59681594],
       [1.        , 0.55908346, 0.52554286, ..., 0.45979658, 0.4472759 ,
        0.44593063],
       [1.        , 0.8928913 , 0.8346261 , ..., 0.74994105, 0.7466907 ,
        0.7286141 ]], dtype=float32)

In [18]:
pk['similar_images'].shape

(1663, 50)

In [29]:
pk['similar_images'][:, :10]

array([[   0,  631,  216, ..., 1349, 1309, 1002],
       [   1,  224,  924, ...,  295,   12,  564],
       [   2,  437, 1135, ...,  940,   20,  920],
       ...,
       [1660, 1384,  870, ...,  277,  436,  414],
       [1661, 1343, 1581, ..., 1398, 1542, 1165],
       [1662,  742, 1373, ...,  972, 1260,  176]])

**pk['cosine_similarities']とpk['similar_images']の構造を確認してみる**

In [33]:
pk['similar_images'][0]

array([   0,  631,  216, 1546,  499,  291,  729, 1349, 1309, 1002, 1484,
        324,  752, 1417, 1200,  266,  268, 1037, 1057, 1419, 1167,  427,
        961, 1594,  337,   92, 1128, 1305, 1338,   66,  976, 1171, 1437,
       1331,  511, 1220, 1281,  761,  628,  955,   79,  929,  172,  540,
       1587,  142,  820,  294,  223, 1102])

In [39]:
pk['image'][[631, 216, 1546]]

array(['151414046745_0.JPG', '151414046745_2.JPG', '151414046745_4.JPG'],
      dtype=object)

In [40]:
pk['cosine_similarities'][0]

array([1.0000001 , 0.7886466 , 0.72532964, 0.6898457 , 0.6698687 ,
       0.6583883 , 0.5936295 , 0.5875672 , 0.5801832 , 0.5326115 ,
       0.531813  , 0.51836765, 0.51715547, 0.5165535 , 0.51010174,
       0.50843626, 0.5003836 , 0.48759025, 0.4758062 , 0.47038227,
       0.46205786, 0.45735425, 0.45551607, 0.45395625, 0.4480823 ,
       0.4463228 , 0.4460118 , 0.4426446 , 0.4391476 , 0.43757942,
       0.43694645, 0.42965487, 0.42964178, 0.429216  , 0.42863777,
       0.42701524, 0.41947827, 0.41864818, 0.4116189 , 0.40659   ,
       0.40293705, 0.40208736, 0.39876264, 0.3904548 , 0.38536176,
       0.38517582, 0.38472462, 0.38408548, 0.3743736 , 0.37117776],
      dtype=float32)

In [42]:
pk['cosine_similarities'][0][1:4]

array([0.7886466 , 0.72532964, 0.6898457 ], dtype=float32)

In [55]:
df[:1]

image         label  fold top_1_similar_image  \
0  151414046745_8.JPG  151414046745     4  151414046745_0.JPG   

   top_1_cosine_similarity top_2_similar_image  top_2_cosine_similarity  \
0                 0.788647  151414046745_2.JPG                  0.72533   

  top_3_similar_image  top_3_cosine_similarity  
0  151414046745_4.JPG                 0.689846

In [45]:
def cos_sim(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [51]:
emb_im0 = pk['embeddings'][0, :]    # 151414046745_8.JPG
emb_im631 = pk['embeddings'][631, :]   # 151414046745_0.JPG

emb_im0.shape, emb_im631.shape

((512,), (512,))

In [52]:
cos_sim(emb_im0, emb_im631)

0.78864664